export enum QueryCacheKey {
    PRODUCTS = 'PRODUCTS',
    CLIENTS = 'CLIENTS',
    TRANSACTIONS = 'TRANSACTIONS',
    LAST_TRANSACTIONS = 'LAST_TRANSACTIONS',
    DETAILS = 'DETAILS',
    CLIENT_TOTAL = 'CLIENT_TOTAL',
    PRODUCT_TOTAL = 'PRODUCT_TOTAL',
    TRANSACTION_TOTAL = 'TRANSACTION_TOTAL',
}